version: '3'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dango
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  es:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  app:
    build: .
    ports:
      - "9090:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - es
    environment:
      DEBUG: 1
      DEBUG_TOOLBAR: 1
      DATABASE_URL: postgres://postgres:secret@db:5432/dango
volumes:
  postgresdata:
