# Generated by Django 3.1.7 on 2021-03-17 07:26

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='podcast_content', to='cms.placeholder'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_audio', slotname='podcast_audio', to='cms.placeholder'),
        ),
    ]
