# Generated by Django 3.1.7 on 2021-03-17 07:44

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('podcast', '0002_auto_20210317_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_content', slotname='podcast_content', to='cms.placeholder'),
        ),
    ]
