# Generated by Django 3.1.7 on 2021-03-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_auto_20210317_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='host',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcast.host'),
        ),
    ]
